name: Run Weather ETL

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-weather-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up .env file from secrets
      run: |
        echo "USER=${{ secrets.DB_USER }}" >> .env
        echo "PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "HOST=${{ secrets.DB_HOST }}" >> .env
        echo "PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DBNAME=${{ secrets.DB_NAME }}" >> .env

    - name: Run weather_etl script
      run: python weather_etl.py
